"""Add Boolean Fiel

Revision ID: 533ffe1b5942
Revises: 
Create Date: 2023-10-24 20:35:31.434334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533ffe1b5942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dersler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('edit_ask', sa.Boolean(), nullable=False),
    sa.Column('test_ask', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dersler')
    # ### end Alembic commands ###
