"""edit Db Column

Revision ID: 68147e33845d
Revises: 533ffe1b5942
Create Date: 2023-10-25 22:53:08.671333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68147e33845d'
down_revision = '533ffe1b5942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dersler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mark_text', sa.Text(), nullable=True))
        batch_op.drop_column('edit_ask')
        batch_op.drop_column('test_ask')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dersler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_ask', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('edit_ask', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('mark_text')
        batch_op.drop_column('edit_text')

    # ### end Alembic commands ###
